### ISSUE TITLE
Sometimes When Player Lands After Taking a High Jump, Collision Detection with Platform Fails

### ISSUE THREAD

**Issue by sbrother** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#1]
Seems to happen only when player did a large "double" jump.

**Comment by cooper51** [comment]
this bug also exists when respawning for new life

**Comment by sbrother** [comment]
fixed in branch 1-fix-platform-collision-a

**Comment by sbrother** [comment]
95% done, needs fix to compensate for higher y-velocity when dropping

**Comment by sbrother** [comment]
fixed and merged with master_candidate
