### ISSUE TITLE
Update Platforms, Midground Objects, and Characters to use Atlas's

### ISSUE THREAD

**Issue by Kovak** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#18]
Added Atlas's in for the midground objects, platforms, and characters. We should switch to using these. Might require a bit of an addition to the animation code to include a reference to the atlas to source the image files from.

**Comment by sbrother** [comment]
Thanks! should be pretty trivial to fix this in AnimationController and
create_scaffold. I didn't write the Midground scroller so I'm not sure
about how much work that is to switch, but I doubt it's too bad

**Comment by sbrother** [comment]
This is part of Issue #19.
