### ISSUE TITLE
Factor out all File IO from Background, Midground, and Foreground classes

### ISSUE THREAD

**Issue by sbrother** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#19]
This will be easiest if we just read all the art assets into one big ass atlas that is read on program **init**, and then anywhere in the code where there is currently file IO, replace it with asset_atlas.get(texture_name)

**Comment by Kovak** [comment]
The maximum safe atlas size is 1024 x 1024 as some of the older devices may have that as the hard limit for the graphics card. Most devices can handle 2048 x 2048 but to be save 1024 x 1024 is probably what we should stick with. However, this is the correct idea!

**Comment by sbrother** [comment]
OK, in that case we should have a ArtAssets class with a get method that determines what the right atlas to query is. The ArtAssets class will basically just be a container for a few atlases.
