### ISSUE TITLE
Enemy and Platform Code Separation

### ISSUE THREAD

**Issue by KerbySmith** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#38]
The main goal of this fix is to separate the code for enemy and platforms, making enemies dependent upon the platforms list found in scrollingforeground, without the scrollingforeground being dependent on enemies.

**Comment by Kovak** [comment]
great work kerby

the rewrites of enemy and world object code make everything much easier to understand and make the code seem a lot simpler to pick up and figure out as well as make modifications

thanks a lot and excellent work today

**Comment by sbrother** [comment]
Just looked at the code and this looks really good, Kerby! Thanks for your
hard work :)

I've been super busy with work today (I have an important meeting with a
client at 9am tomorrow) but I am looking forward to checking off some more
issues after that is done! Sorry I wasn't around so much today and
yesterday.
