### ISSUE TITLE
Creating a new master_candidate

### ISSUE THREAD

**Issue by Kovak** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#40]
Hey Everyone,

I think we should merge quite a few of these branches into a new master candidate

my current vote for branches we should merge is:

22-a

23-a

26-a

27-a

31-a

32-a

33-a

34-a

38-a (which i believe actually contains 34-a as well)

what do ya'll think

**Comment by sbrother** [comment]
I will review these in an hour and vote.

What time do yall want to meet tomorrow?

**Comment by sbrother** [comment]
Just looked at all of these branches and the code looks great! I am way down to make a new master candidate tonight including all these.

Do we not want to also include the memory profiler (25-a) in the master candidate? It seems like a good way to test the performance of code changes going forward.

**Comment by KerbySmith** [comment]
These branches look good to me I'm all for it. I also agree with Sam about adding 25-a to the list.

**Comment by KerbySmith** [comment]
And as for our meeting tomorrow, anytime after 530 Utah time would work for me.

**Comment by Kovak** [comment]
I am not available anytime between 5:50 pm and about 6:45 pm utah time

So I was thinking, at least at the moment there is no reason to have the memory and cpu profiles in the actual master branch as we'd just have to delete them every time we wanted to build for android and ios since they're not really useful for that

what about having a special testing branch or just a repository of code that can be merged into any branch for testing

**Comment by sbrother** [comment]
I like that idea. I'll make a kivy-profiler repo in chaosbuffalo labs and
basically just put ready to run scripts in it that can be copy pasted into
any directory.

**Comment by KerbySmith** [comment]
branches 22, 23, 27, 32, 33, 34, and 38 have been merged into master_candidate. There are merge conflicts with 26 and 31 so those still need to be merged.

**Comment by KerbySmith** [comment]
branch 26 has been merged. 31 is the last one that needs to be merged. I have to head out right now though but i'll talk to you guys at 1030.

**Comment by sbrother** [comment]
After someone, checks it, let's also merge in 1-fix-platform-collision-a, it fixes the problem with players falling through platforms at low framerates.

**Comment by Kovak** [comment]
looks good to me lets merge that one in too

**Comment by sbrother** [comment]
I've merged in 1-a. Tried to merge in 31-a but had weird issues with merge resolution. We'll talk about that during the meeting
