### ISSUE TITLE
New Game creates another instance of Game over old one and weird shit happens

### ISSUE THREAD

**Issue by sbrother** [Kovak/CBL_SECRET_PROTOTYPE_RUNNING_GAME#8]

**Comment by KerbySmith** [comment]
It no longer (visually) loads over the old screen but there is definately something still going on behind the scenes. Haven't figured out how to remove the old game yet once player has died.

**Comment by sbrother** [comment]
Did you do something to remove it visually, or did that happen as a side effect of other code we added?

**Comment by KerbySmith** [comment]
No I did something, check out the ReplayScreen code. It doesn't really fix the problem but it makes it so it can run. I was just investigating how to fix it.

**Comment by sbrother** [comment]
Added a game stop method that fixes this issue.
